### ISSUE TITLE
How to use running container?

### ISSUE THREAD

**Issue by crypdick** [etherealvisage/silvius-docker#1]
First of all, thanks a lot for making this container. I was having a hard time compiling from source.

I ran [your script](https://gist.github.com/etherealvisage/2207fd2fe6229b275edeeacacc7a29e7) (changing the IP to 127.0.1.1).

Now, how am I supposed to use the server? I tried `python2 stream/mic.py -s 127.0.1.1 -d 8 | python2 grammar/main.py` and I get the following error:

```
Content-Type: audio/x-raw, layout=(string)interleaved, rate=(int)16000, format=(string)S16LE, channels=(int)1
Connecting to ws://127.0.1.1:8019/client/ws/speech?content-type=audio%2Fx-raw%2C+layout%3D%28string%29interleaved%2C+rate%3D%28int%2916000%2C+format%3D%28string%29S16LE%2C+channels%3D%28int%291
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Using mic # 8

LISTENING TO MICROPHONE
Received error from server (status 9)
Error message: No decoder available, try again later
ok

```

Here's the output of `docker container ls`:

```
docker container ls
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                      NAMES
4e72ba65bf2d        voxhub/silvius-worker          "/root/worker.sh -u …"   20 minutes ago      Up 20 minutes                                  elated_rosalind
c7c004422cc6        voxhub/silvius-worker:latest   "/bin/sh -c 'cd /roo…"   20 minutes ago      Up 20 minutes       127.0.1.1:8019->8019/tcp   adoring_boyd
```

I also tried all the other microphones from `python2 stream/list-mics.py` but I get similar errors.

**Comment by crypdick** [comment]
I figured it out with the help of @dwks. I had to find the host IP of the server using `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_name>`, then using that IP when starting the worker. Finally, connecting to that IP using `stream/mic.py`.

**Comment by etherealvisage** [comment]
Ah, sorry, saw this last night and was just about to take a look. Good to hear you and @dwks were able to get things working --- let me know if anything else comes up and I'll try to help.
